import{a as y,i as d,S as m}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const f=document.getElementById("search-form"),c=document.getElementById("gallery"),i=document.querySelector(".loader"),p=document.getElementById("load-more"),a={key:"42152673-4f3b2f2010df91e54c05d1b70",image_type:"photo",orientation:"horizontal",safesearch:!0,q:"",page:1,per_page:15};f.addEventListener("submit",async function(e){e.preventDefault(),i.style.display="block";const r=e.target.elements.input.value;a.q=r,a.page=1;try{const n=await g();h(n)}catch(n){console.error(n)}e.target.reset()});p.addEventListener("click",async function(){i.style.display="block",a.page++;try{const e=await g();u(e)}catch(e){console.error(e)}});async function g(){try{return(await y.get("https://pixabay.com/api/",{params:a})).data}catch(e){throw new Error(e.response.status)}}function h(e){e.hits.length===0?(d.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",backgroundColor:"#EF4040",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"}),c.innerHTML="",p.style.display="none"):(c.innerHTML="",u(e),p.style.display="block"),i.style.display="none"}function u(e){const r=e.hits.map(o=>`<a class="gallery-link" href="${o.largeImageURL}">
      <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
      <div class="image-info">
        <p ><strong>Likes:</strong> <span class="text">${o.likes}</span></p>
        <p ><strong>Views:</strong> <span class="text">${o.views}</span></p>
        <p ><strong>Comments:</strong> <span class="text">${o.comments}</span></p>
        <p ><strong>Downloads:</strong> <span class="text">${o.downloads}</span></p>
      </div>
    </a>`).join("");c.insertAdjacentHTML("beforeend",r),i.style.display="none",a.page*15>=e.totalHits&&(loadMoreBtn.style.display="none",d.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#FFFFFF",backgroundColor:"#EF4040",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"})),new m(".gallery-link").refresh()}
//# sourceMappingURL=commonHelpers.js.map
