import{a as u,i as d,S as m}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const f=document.getElementById("search-form"),p=document.getElementById("gallery"),a=document.querySelector(".loader"),l=document.getElementById("load-more"),h="42152673-4f3b2f2010df91e54c05d1b70",i={key:h,image_type:"photo",orientation:"horizontal",safesearch:!0,q:"",page:1,per_page:15};f.addEventListener("submit",async function(e){e.preventDefault(),a.style.display="block";const r=e.target.elements.input.value;i.q=r,i.page=1;try{const n=await g();b(n)}catch(n){console.error(n)}e.target.reset()});l.addEventListener("click",async function(){a.style.display="block",i.page++;try{const e=await g();y(e)}catch(e){console.error(e)}});async function g(){try{return(await u.get("https://pixabay.com/api/",{params:i})).data}catch(e){throw new Error(e.response.status)}}function b(e){e.hits.length===0?(d.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",backgroundColor:"#EF4040",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"}),p.innerHTML="",l.style.display="none"):(p.innerHTML="",y(e),l.style.display="block"),a.style.display="none"}function y(e){a.style.display="block";const r=e.hits.map(o=>`<a class="gallery-link" href="${o.largeImageURL}">
      <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
      <div class="image-info">
        <p ><strong>Likes:</strong> <span class="text">${o.likes}</span></p>
        <p ><strong>Views:</strong> <span class="text">${o.views}</span></p>
        <p ><strong>Comments:</strong> <span class="text">${o.comments}</span></p>
        <p ><strong>Downloads:</strong> <span class="text">${o.downloads}</span></p>
      </div>
    </a>`).join("");p.insertAdjacentHTML("beforeend",r),a.style.display="none",i.page*15>=e.totalHits&&(l.style.display="none",d.show({message:"We're sorry, but you've reached the end of search results.",messageColor:"#FFFFFF",backgroundColor:"#EF4040",position:"topRight",messageSize:"16px",messageLineHeight:"24px",maxWidth:"432px"})),new m(".gallery-link").refresh()}
//# sourceMappingURL=commonHelpers.js.map
